apiVersion: v1
kind: Service
metadata:
  name: python-web-service
  namespace: default
spec:
  type: NodePort
  selector:
    app: python-web-app
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
